name: ARShopUTC
description: A web app for AR Shop
version: 0.5.0
homepage: https://fjreyna.me

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
  angular_bloc: ^6.0.0-dev.6
  bloc: ^6.0.3

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.9.0
  build_test: ^1.0.0
  build_web_compilers: ^2.10.0
  pedantic: ^1.9.0
  test: ^1.6.3
